# Generated by Django 4.2.6 on 2023-11-02 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_category_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cover_letter', models.TextField(help_text='add your notes here', max_length=200)),
                ('cv', models.FileField(help_text='please upload your cv', upload_to='CVS')),
                ('linkedin_profile', models.URLField(blank=True, help_text='please enter your LinkedIn profile url', null=True)),
                ('github_profile', models.URLField(blank=True, help_text='please enter your github profile url', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job')),
            ],
        ),
    ]
