# Generated by Django 4.2.6 on 2023-11-02 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_options_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='cv',
            field=models.FileField(help_text='please upload your cv', upload_to='CVS', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
