# Generated by Django 4.2.6 on 2023-11-03 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobapply_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='cv',
            field=models.FileField(help_text='please upload your cv', upload_to='CVS', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed')]),
        ),
    ]
